modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="superfluousmod"
version="1.0.0"
displayName="SuperfluousMod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Vader, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.superfluousmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



